/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pcsstandalone.userinterface;

import Controller.DataBaseConnection;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nagarjun Reddy
 */
public class Employee_Watch extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public static String username;
    public static String videoname;
    private String fileName;
    public Employee_Watch() {
        initComponents();
        jTextField1.setText(videoname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 100, 50));

        jButton2.setText("Courses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 110, 50));

        jButton4.setText("upload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, 50));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Video name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 30));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("comment:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        jButton5.setText("Comment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Discussion forum");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jButton1.setText("Post");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        jButton3.setText("Watch Video");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, -1, 27));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 690, 210));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 320, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 290, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nagarjun Reddy\\Desktop\\PCSStandalone\\src\\pcsstandalone\\userinterface\\main.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        WelcomeScreen.main(username);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //courses
        this.setVisible(false);
        Employee_courses.main(username);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        upload_video.main(username);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         //TODO add your handling code here:
                        this.setVisible(false);
                        String comment=jTextArea2.getText();
                        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                        Date date = new Date();
                        String d;
                        d = (String)dateFormat.format(date);
                        Connection conn = null;
                        try {
                        try {
                                conn = DataBaseConnection.dbConnection();
                            } catch (    ClassNotFoundException | SQLException ex) {
                                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
                            }
                                    PreparedStatement ps;
                                    ps=(PreparedStatement) conn.prepareStatement("Insert into comments values(?,?,?,?)");
                                    ps.setString(1, d);//date
                        	    ps.setString(2, username);//user name
                        	    ps.setString(3, videoname);//video name
                        	    ps.setString(4, comment);//comment
                                    ps.execute();
                                    FileWriter fileWriter = null;
                                    try {
                                                fileWriter = new FileWriter("C://Program Files/PCS/comments.txt",true);
                                            } catch (IOException ex) {
                                                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                    try (BufferedWriter bufferedWriter = new BufferedWriter(fileWriter)) {
                                                bufferedWriter.write(d+" "+username+" "+videoname+" "+comment+"*");
                                                bufferedWriter.close();
                                            }
                                } catch (SQLException | IOException ex) {
                                    Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
                                }
                        //SE connectio
                        Connection conn1 = null;
                        try {
                                conn1 = DataBaseConnection.dbConnection1();
                            } catch (    ClassNotFoundException | SQLException ex) {
                                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
                            }
                                    PreparedStatement ps1 = null;
        try {
            ps1=(PreparedStatement) conn1.prepareStatement("Insert into comments values(?,?,?,?)");
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(1, d);//date
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(2, username);//user name
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(3, videoname);//video name
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(4, comment);//comment
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
        }
                                
        Employee_Watch.main(username,videoname);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MediaPlayer.main(videoname);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        String que=jTextArea1.getText();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        String d;
        d = (String)dateFormat.format(date);
        Connection conn = null;
        try {
            try {
                conn = DataBaseConnection.dbConnection();
            } catch (    ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps = null;
            try {
                ps=(PreparedStatement) conn.prepareStatement("Insert into form values(?,?,?,?)");
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps.setString(1, username);//user name
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps.setString(2, que);//question
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps.setString(3, videoname);//video name
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps.setString(4, d);//date
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            FileWriter fileWriter = null;
            try {
                fileWriter = new FileWriter("C://Program Files/PCS/discussion.txt",true);
            } catch (IOException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try (BufferedWriter bufferedWriter = new BufferedWriter(fileWriter)) {
                bufferedWriter.write(username+" "+que+" "+videoname+" "+d+"*");
                bufferedWriter.close();
            }
        }
        catch(IOException ex) {
            System.out.println("Error writing to file '"+ fileName + "'");
            // Or we could just do this:
            // ex.printStackTrace();
        }
        /*
          connect to SE
         */
        Connection conn1 = null;
       
            try {
                conn1 = DataBaseConnection.dbConnection1();
            } catch (    ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps1 = null;
            try {
                ps1=(PreparedStatement) conn1.prepareStatement("Insert into form values(?,?,?,?)");
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps1.setString(1, username);//user name
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps1.setString(2, que);//question
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps1.setString(3, videoname);//video name
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps1.setString(4, d);//date
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ps1.execute();
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Watch.class.getName()).log(Level.SEVERE, null, ex);
            }
        Employee_Watch.main(username,videoname);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String username1,String videoname1) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Employee_Watch.username=username1;
        Employee_Watch.videoname=videoname1;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Employee_Watch().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
