/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pcsstandalone.userinterface;

import Controller.DataBaseConnection;
import com.mysql.jdbc.PreparedStatement;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Nagarjun Reddy
 */
public class upload_video extends javax.swing.JFrame{

    /**
     * Creates new form Employee_serach_video
     */
   public static String username=null;
   File[] f;
   // public static String keyword;
    public upload_video() {
        initComponents();    
        try {
            Connection con=DataBaseConnection.dbConnection();
            Statement stmt=con.createStatement();
            String courses="select course from courses";
            ResultSet rs=stmt.executeQuery(courses);
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("course"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Employee_courses.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jButton2.setText("Course");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 113, 40));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Video name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 150, 30));

        jButton3.setText("Upload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 90, 40));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 700, 124));

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 90, 10));

        jButton4.setText("search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 110, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Courses" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 113, 40));

        jButton1.setText("File chooser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 151, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 173, 23));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nagarjun Reddy\\Desktop\\PCSStandalone\\src\\pcsstandalone\\userinterface\\main.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //courses
        this.setVisible(false);
        Employee_courses.main(username);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        String video=jTextField1.getText();
        String dec=jTextField2.getText();
        String Course=(String) jComboBox1.getSelectedItem();
         Connection conn;
        try {
            conn = DataBaseConnection.dbConnection();
            PreparedStatement ps=(PreparedStatement) conn.prepareStatement("Insert into videos values(?,?,?,?,?)");
            ps.setString(1, video);//video name
	    ps.setString(2, dec);//description
	    ps.setInt(3, 0);//Like
	    ps.setInt(4, 0);//unlike
	    ps.setString(5, Course);//course
            ps.execute();
            ps.close();
            ps=(PreparedStatement) conn.prepareStatement("Insert into upload values(?,?,?,?,?)");
            ps.setString(1, video);//video name
	    ps.setString(2, dec);//description
	    ps.setInt(3, 0);//Like
	    ps.setInt(4, 0);//unlike
	    ps.setString(5, Course);//course
            ps.execute();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        //SE upload
        Connection conn1 = null;
        try {
            conn1 = DataBaseConnection.dbConnection1();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
            PreparedStatement ps1 = null;
        try {
            ps1 = (PreparedStatement) conn1.prepareStatement("Insert into videos values(?,?,?,?,?)");
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(1, video);//video name
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(2, dec);//description
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setInt(3, 0);//Like
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setInt(4, 0);//unlike
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.setString(5, Course);//course
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ps1.execute();
        } catch (SQLException ex) {
            Logger.getLogger(upload_video.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Employee_search_video_results.main(keyword);
        WelcomeScreen.main(username);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Employee_search.main(username);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        WelcomeScreen.main(username);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        int option = chooser.showOpenDialog(upload_video.this);
        if (option == JFileChooser.APPROVE_OPTION) 
        {
          f = chooser.getSelectedFiles(); 
         
          String filelist = "nothing";
          if (f.length > 0) 
          {
                filelist = f[0].getName();
          }
          for (int i = 1; i < f.length; i++) 
          {
                filelist += ", " + f[i].getName();
          }
            jLabel6.setText("You choose " + filelist);
        }
        else 
        {
          jLabel6.setText("You canceled.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String username1) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upload_video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        upload_video.username=username1;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new upload_video().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
